# Generated by Django 4.2.3 on 2023-07-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lectures_duration_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectures',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='lectures',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='lectures',
            name='start_time',
        ),
    ]
